### PR TITLE
WIP: Databricks with KFP

### PR DESCRIPTION
**Pull request by sylus**

### CODE REVIEW

**Comment by sylus** [comment]
This should resolve issue #7 when is done.

**Comment by blairdrummond** [comment]
Can you show @ca-scribner  how to translate some of this to a `pyspark` example? It looks like Steve actually already did this

https://medium.com/@szinck/setting-up-pyspark-jupyter-and-minio-on-kubeflow-kubernetes-aab98874794f

I think Andrew just needs a hand learning about the kubernetes plumbing involved here. That way people will be able to both send Spark jobs with pipelines & use it interactively as a pandas replacement with spark dataframes

**Comment by sylus** [comment]
@blairdrummond can u get Steven to handle that part after this commit I have to move onto some security controls but this should serve as a good base.

**Comment by blairdrummond** [comment]
Sure thing!

**Comment by ca-scribner** [comment]
Yeah Steve and I were actually talking about this when Blair @'d me but I hadn't seen this commit.  We'll talk it through

**Pull request merged**
